version: "3.8"
services:
  typer-db:
    build: ./db
    ports:
      - '5432:5432'
    env_file:
      - ./env/db.env

  typer-backend:
    build: ./
    ports:
      - '8080:8080'
    volumes:
      - batchfiles:/app/batchfiles
    depends_on:
      - typer-db
    env_file:
      - ./env/db.env

  typer-web:
    build: ./web
    ports:
      - '4200:80'
    depends_on:
      - typer-backend

volumes:
  batchfiles: