apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: typer-backend
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: DB_ADDRESS
              value: {{ .Values.env.value.DB_ADDRESS }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretRef.name }}
          volumeMounts:
            - mountPath: /app/batchfiles
              name: batchfiles-volume
      volumes:
        - name: batchfiles-volume
          emptyDir: {}