apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: typer-db
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          envFrom:
            - secretRef:
                name: {{ .Values.secretRef.name }}
