apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432