apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: typer-web
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: BACKEND_ADDRESS
              value: "{{ .Values.env.value.BACKEND_ADDRESS }}.{{ .Values.namespace }}"