apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typer-backend
  template:
    metadata:
      labels:
        app: typer-backend
    spec:
      containers:
        - name: typer-backend
          image: rafiki90/typer-backend:latest
          env:
            - name: DB_ADDRESS
              value: "db-service.default"
          envFrom:
            - secretRef:
                name: db-secret
          volumeMounts:
            - mountPath: /app/batchfiles
              name: batchfiles-volume
      volumes:
        - name: batchfiles-volume
          emptyDir: {}