apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typer-web
  template:
    metadata:
      labels:
        app: typer-web
    spec:
      containers:
        - name: typer-web
          image: rafiki90/typer-web:latest